name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  animations: ^2.0.11
  auto_route: ^8.1.3
  bloc: ^8.1.4
  dotted_line: ^3.2.2
  either_dart: ^1.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  page_transition: ^2.1.0
  supabase_flutter: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/munch.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Thin.ttf
          weight: 100
        - asset: assets/font/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter-Black.ttf
          weight: 900
